/**
 * Landscape interpretation.
 *
 * A map shows you a field of colour. What a land manager actually asks is: where is it
 * worst, is that unusual, and what about this place makes it so. This answers those from
 * the cell grid, arithmetically.
 *
 * Nothing here is generated by a model. Every sentence the console renders is assembled
 * from numbers computed in SQL over validated cells, which is the same rule the rest of the
 * layer runs on — the interpretation of a measurement is a quantitative claim, and it gets
 * held to the same standard as the measurement.
 *
 * The join that makes it work: cell ids end in `:row:col`, and every layer is aggregated
 * onto the same grid, so a spectral cell and a terrain cell with the same suffix describe
 * the same 500 m of ground. That lets any layer be broken down by elevation, aspect or
 * slope without a spatial join.
 */

import { CATEGORICAL_INDICATORS, dryingDirection } from "@gaia/core";

import { query, num, str } from "./db.js";
import { IndicatorNotInterpretableError, NoDataForPeriodError } from "./errors.js";

/** `val_abc:12:34` -> `12:34`. Value ids never contain a colon. */
const CELL_POSITION = "regexp_extract(cell_id, ':(\\d+:\\d+)$', 1)";

export interface Distribution {
  count: number;
  min: number;
  p10: number;
  p25: number;
  median: number;
  p75: number;
  p90: number;
  max: number;
  mean: number;
  std: number;
}

export interface ZonalBand {
  band: string;
  cells: number;
  share: number;
  mean: number;
  median: number;
}

export interface Correlation {
  against: string;
  r: number;
  strength: "none" | "weak" | "moderate" | "strong";
  direction: "positive" | "negative";
  n: number;
}

export interface Interpretation {
  aoi_id: string;
  indicator: string;
  period: { start: string; end: string };
  units: string;
  distribution: Distribution;
  by_elevation: ZonalBand[];
  by_aspect: ZonalBand[];
  by_slope: ZonalBand[];
  correlations: Correlation[];
  extremes: {
    threshold: number;
    cells: number;
    share: number;
    mean_elevation_m: number | null;
    dominant_aspect: string | null;
    mean_slope_deg: number | null;
  };
  departure: { mean: number; drier_share: number; strongly_drier_share: number } | null;
  readings: string[];
  generated_at: string;
}

/**
 * Aspect octant from degrees clockwise from north.
 *
 * Kept as SQL rather than post-processing because the grouping has to happen before the
 * aggregate, and because aspect is circular — the north class straddles 0°, which is the
 * one part of this that is easy to get wrong.
 */
const ASPECT_CASE = `
  CASE
    WHEN t.aspect IS NULL THEN 'flat'
    WHEN t.aspect >= 337.5 OR t.aspect < 22.5 THEN 'N'
    WHEN t.aspect < 67.5 THEN 'NE'
    WHEN t.aspect < 112.5 THEN 'E'
    WHEN t.aspect < 157.5 THEN 'SE'
    WHEN t.aspect < 202.5 THEN 'S'
    WHEN t.aspect < 247.5 THEN 'SW'
    WHEN t.aspect < 292.5 THEN 'W'
    ELSE 'NW'
  END`;

/** Terrain cells keyed by grid position, as a CTE every zonal query reuses. */
const TERRAIN_CTE = `
  terrain AS (
    SELECT ${CELL_POSITION} AS pos,
           max(CASE WHEN indicator = 'elevation_m' THEN value END) AS elevation,
           max(CASE WHEN indicator = 'aspect_deg' THEN value END) AS aspect,
           max(CASE WHEN indicator = 'slope_deg' THEN value END) AS slope,
           max(CASE WHEN indicator = 'twi' THEN value END) AS twi
    FROM lake.indicator_cell
    WHERE aoi_id = $1 AND indicator IN ('elevation_m', 'aspect_deg', 'slope_deg', 'twi')
    GROUP BY 1
  )`;

function strengthOf(r: number): Correlation["strength"] {
  const a = Math.abs(r);
  if (a < 0.15) return "none";
  if (a < 0.35) return "weak";
  if (a < 0.6) return "moderate";
  return "strong";
}

const LABELS: Record<string, string> = {
  ndvi: "vegetation greenness",
  ndmi: "canopy moisture",
  nbr: "burn ratio",
  substrate_score: "substrate score",
  elevation_m: "elevation",
  slope_deg: "slope",
  aspect_deg: "aspect",
  twi: "topographic wetness",
  heat_load: "heat load",
  dnbr: "burn severity",
};

/** Suffixes a derived layer carries, and what the reading calls them. */
const SUFFIXES: ReadonlyArray<readonly [string, string]> = [
  ["_departure", "departure"],
  ["_annual_min", "annual low"],
  ["_amplitude", "seasonal swing"],
];

function labelFor(indicator: string): string {
  for (const [suffix, phrase] of SUFFIXES) {
    if (indicator.endsWith(suffix)) {
      return `${LABELS[indicator.slice(0, -suffix.length)] ?? indicator} ${phrase}`;
    }
  }
  return LABELS[indicator] ?? indicator;
}

/** True when a higher number means drier, more fire-prone ground. */
function higherIsDrier(indicator: string): boolean {
  return dryingDirection(indicator) === "up";
}

/**
 * Terrain variables a layer must not be correlated against, because it is computed from
 * them.
 *
 * "Elevation tracks elevation upward, r = 1.00" is not a finding, and neither is topographic
 * wetness against the slope in its own denominator. A correlation that the formula
 * guarantees tells a reader nothing about this landscape, and printing it next to real
 * correlations invites them to weigh the two the same way.
 */
const CIRCULAR_AGAINST: Record<string, ReadonlySet<string>> = {
  // Aspect shares no term with any of the three, and is listed with nothing to drop so
  // that membership of this table can also stand for "this layer is landform itself".
  aspect_deg: new Set(),
  elevation_m: new Set(["elevation"]),
  slope_deg: new Set(["slope", "topographic wetness"]),
  twi: new Set(["slope", "topographic wetness"]),
  heat_load: new Set(["slope"]),
};

export async function interpretLayer(
  aoiId: string,
  indicator: string,
  periodStart: string,
): Promise<Interpretation> {
  if (CATEGORICAL_INDICATORS.has(indicator)) {
    throw new IndicatorNotInterpretableError(
      indicator,
      "Its values are class codes rather than quantities, so quantiles, zonal means and " +
        "correlations against terrain would all be arithmetic on labels.",
    );
  }

  const base = [aoiId, indicator, periodStart];

  const [dist] = await query(
    `SELECT count(*) AS n, min(value) AS lo, max(value) AS hi,
            avg(value) AS mean, stddev_pop(value) AS sd,
            quantile_cont(value, 0.10) AS p10, quantile_cont(value, 0.25) AS p25,
            quantile_cont(value, 0.50) AS p50, quantile_cont(value, 0.75) AS p75,
            quantile_cont(value, 0.90) AS p90,
            any_value(period_end) AS period_end
     FROM lake.indicator_cell
     WHERE aoi_id = $1 AND indicator = $2 AND period_start = $3 AND value IS NOT NULL`,
    base,
  );

  if (dist === undefined || num(dist["n"]) === 0) {
    throw new NoDataForPeriodError(`${indicator} at ${periodStart}`);
  }

  const distribution: Distribution = {
    count: num(dist["n"]),
    min: num(dist["lo"]),
    p10: num(dist["p10"]),
    p25: num(dist["p25"]),
    median: num(dist["p50"]),
    p75: num(dist["p75"]),
    p90: num(dist["p90"]),
    max: num(dist["hi"]),
    mean: num(dist["mean"]),
    std: num(dist["sd"]),
  };

  const layerCte = `
    layer AS (
      SELECT ${CELL_POSITION} AS pos, value
      FROM lake.indicator_cell
      WHERE aoi_id = $1 AND indicator = $2 AND period_start = $3 AND value IS NOT NULL
    )`;

  // ---------------------------------------------------------------- zonal breakdowns
  const byElevation = await query(
    `WITH ${layerCte}, ${TERRAIN_CTE}
     SELECT CASE
              WHEN t.elevation < 50 THEN '0–50 m'
              WHEN t.elevation < 150 THEN '50–150 m'
              WHEN t.elevation < 300 THEN '150–300 m'
              WHEN t.elevation < 600 THEN '300–600 m'
              ELSE '600 m+'
            END AS band,
            count(*) AS cells, avg(l.value) AS mean, median(l.value) AS med,
            min(t.elevation) AS sort_key
     FROM layer l JOIN terrain t USING (pos)
     WHERE t.elevation IS NOT NULL
     GROUP BY band ORDER BY sort_key`,
    base,
  );

  const byAspect = await query(
    `WITH ${layerCte}, ${TERRAIN_CTE}
     SELECT ${ASPECT_CASE} AS band, count(*) AS cells,
            avg(l.value) AS mean, median(l.value) AS med
     FROM layer l JOIN terrain t USING (pos)
     GROUP BY band ORDER BY mean DESC`,
    base,
  );

  const bySlope = await query(
    `WITH ${layerCte}, ${TERRAIN_CTE}
     SELECT CASE
              WHEN t.slope < 5 THEN 'flat, under 5°'
              WHEN t.slope < 15 THEN 'gentle, 5–15°'
              WHEN t.slope < 30 THEN 'moderate, 15–30°'
              ELSE 'steep, over 30°'
            END AS band,
            count(*) AS cells, avg(l.value) AS mean, median(l.value) AS med,
            min(t.slope) AS sort_key
     FROM layer l JOIN terrain t USING (pos)
     WHERE t.slope IS NOT NULL
     GROUP BY band ORDER BY sort_key`,
    base,
  );

  const toBands = (rows: Record<string, unknown>[]): ZonalBand[] => {
    const total = rows.reduce((a, r) => a + num(r["cells"]), 0);
    return rows.map((r) => ({
      band: str(r["band"]),
      cells: num(r["cells"]),
      share: total === 0 ? 0 : num(r["cells"]) / total,
      mean: num(r["mean"]),
      median: num(r["med"]),
    }));
  };

  // ------------------------------------------------------------------- correlations
  const [corr] = await query(
    `WITH ${layerCte}, ${TERRAIN_CTE}
     SELECT corr(l.value, t.elevation) AS r_elev,
            corr(l.value, t.slope) AS r_slope,
            corr(l.value, t.twi) AS r_twi,
            count(*) AS n
     FROM layer l JOIN terrain t USING (pos)`,
    base,
  );

  const circular = CIRCULAR_AGAINST[indicator.replace(/_(departure|annual_min|amplitude)$/, "")];

  const correlations: Correlation[] = (
    [
      ["elevation", num(corr?.["r_elev"] ?? Number.NaN)],
      ["slope", num(corr?.["r_slope"] ?? Number.NaN)],
      ["topographic wetness", num(corr?.["r_twi"] ?? Number.NaN)],
    ] as [string, number][]
  )
    .filter(([against]) => circular?.has(against) !== true)
    .filter(([, r]) => Number.isFinite(r))
    .map(([against, r]) => ({
      against,
      r,
      strength: strengthOf(r),
      direction: r >= 0 ? ("positive" as const) : ("negative" as const),
      n: num(corr?.["n"] ?? 0),
    }));

  // ----------------------------------------------------------------------- extremes
  //
  // The decile at the fire-prone end, whichever end that is for this indicator.
  const driestHigh = higherIsDrier(indicator);
  const threshold = driestHigh ? distribution.p90 : distribution.p10;
  const comparison = driestHigh ? ">=" : "<=";

  const [ext] = await query(
    `WITH ${layerCte}, ${TERRAIN_CTE}
     SELECT count(*) AS cells, avg(t.elevation) AS elev, avg(t.slope) AS slope
     FROM layer l LEFT JOIN terrain t USING (pos)
     WHERE l.value ${comparison} $4`,
    [...base, threshold],
  );

  const [extAspect] = await query(
    `WITH ${layerCte}, ${TERRAIN_CTE}
     SELECT ${ASPECT_CASE} AS band, count(*) AS cells
     FROM layer l JOIN terrain t USING (pos)
     WHERE l.value ${comparison} $4
     GROUP BY band ORDER BY cells DESC LIMIT 1`,
    [...base, threshold],
  );

  // -------------------------------------------------------------------- departure
  //
  // How much of the area is drier than its own normal, which is a different question
  // from how dry it is.
  const departureLayer = indicator.endsWith("_departure")
    ? indicator
    : ["ndmi", "ndvi", "nbr"].includes(indicator)
      ? `${indicator}_departure`
      : null;

  let departure: Interpretation["departure"] = null;
  if (departureLayer !== null) {
    const [dep] = await query(
      `SELECT avg(value) AS mean,
              avg(CASE WHEN value < 0 THEN 1.0 ELSE 0.0 END) AS drier,
              avg(CASE WHEN value < -0.05 THEN 1.0 ELSE 0.0 END) AS much_drier
       FROM lake.indicator_cell
       WHERE aoi_id = $1 AND indicator = $2 AND period_start = $3 AND value IS NOT NULL`,
      [aoiId, departureLayer, periodStart],
    );
    if (dep !== undefined && Number.isFinite(num(dep["mean"]))) {
      departure = {
        mean: num(dep["mean"]),
        drier_share: num(dep["drier"]),
        strongly_drier_share: num(dep["much_drier"]),
      };
    }
  }

  const interpretation: Interpretation = {
    aoi_id: aoiId,
    indicator,
    period: { start: periodStart, end: str(dist["period_end"]).slice(0, 10) },
    units: indicator === "substrate_score" ? "score 0–100" : "index",
    distribution,
    by_elevation: toBands(byElevation),
    by_aspect: toBands(byAspect),
    by_slope: toBands(bySlope),
    correlations,
    extremes: {
      threshold,
      cells: num(ext?.["cells"] ?? 0),
      share: distribution.count === 0 ? 0 : num(ext?.["cells"] ?? 0) / distribution.count,
      mean_elevation_m: Number.isFinite(num(ext?.["elev"] ?? Number.NaN))
        ? num(ext?.["elev"])
        : null,
      dominant_aspect: extAspect === undefined ? null : str(extAspect["band"]),
      mean_slope_deg: Number.isFinite(num(ext?.["slope"] ?? Number.NaN))
        ? num(ext?.["slope"])
        : null,
    },
    departure,
    readings: [],
    generated_at: new Date().toISOString(),
  };

  interpretation.readings = compose(interpretation);
  return interpretation;
}

/**
 * The written read.
 *
 * Every clause is a direct function of a number above. Templates rather than prose
 * generation, for the same reason the rest of the layer refuses to let a model near a
 * figure: a sentence that characterises a measurement is a claim about it.
 */
function compose(i: Interpretation): string[] {
  const out: string[] = [];
  const name = labelFor(i.indicator);
  const d = i.distribution;
  const fmt = (n: number): string => (i.indicator === "substrate_score" ? n.toFixed(1) : n.toFixed(3));

  out.push(
    `Across ${d.count.toLocaleString()} cells of 500 m, ${name} runs from ${fmt(d.min)} to ` +
      `${fmt(d.max)}, with a median of ${fmt(d.median)} and the middle half between ` +
      `${fmt(d.p25)} and ${fmt(d.p75)}.`,
  );

  const spread = d.p90 - d.p10;
  const relative = Math.abs(d.median) > 1e-6 ? spread / Math.abs(d.median) : 0;
  out.push(
    relative > 0.5
      ? `The landscape is heterogeneous: the tenth and ninetieth percentiles differ by ` +
        `${fmt(spread)}, so an area-wide average conceals a wide range of local conditions.`
      : `The field is comparatively uniform, with ${fmt(spread)} separating the tenth and ` +
        `ninetieth percentiles — an area-wide figure represents most of this landscape well.`,
  );

  // A terrain layer is landform already, so the usual "terrain rather than vegetation"
  // gloss says nothing about it. It gets the correlation and no interpretation of it.
  const isTerrain = CIRCULAR_AGAINST[i.indicator] !== undefined;

  const strongest = [...i.correlations]
    .filter((c) => c.strength !== "none")
    .sort((a, b) => Math.abs(b.r) - Math.abs(a.r))[0];
  if (strongest !== undefined) {
    out.push(
      `${name[0]?.toUpperCase()}${name.slice(1)} tracks ${strongest.against} ` +
        `${strongest.direction === "positive" ? "upward" : "downward"} ` +
        `(r = ${strongest.r.toFixed(2)}, ${strongest.strength}, n = ${strongest.n.toLocaleString()})` +
        (isTerrain
          ? `.`
          : `, so terrain explains part of what the map shows rather than it being ` +
            `vegetation alone.`),
    );
  } else if (i.correlations.length > 0) {
    const weakest =
      `No terrain variable correlates meaningfully with ${name} at this scale ` +
      `(strongest |r| = ${Math.max(...i.correlations.map((c) => Math.abs(c.r))).toFixed(2)})`;
    out.push(
      isTerrain
        ? `${weakest}.`
        : `${weakest}, which points at land cover and management rather than landform.`,
    );
  }

  const aspects = i.by_aspect.filter((b) => b.band !== "flat");
  const worst = aspects[0];
  const best = aspects[aspects.length - 1];
  if (worst !== undefined && best !== undefined && worst.band !== best.band) {
    const gap = Math.abs(worst.mean - best.mean);
    if (gap > (i.indicator === "substrate_score" ? 1.5 : 0.015)) {
      // Only claim the solar explanation when the data actually shows it. In the northern
      // hemisphere the sun-exposed aspects are S through W; if the extreme sits on a north
      // face instead, something other than insolation is driving it and saying otherwise
      // would be a tidy sentence contradicting the number above it.
      const sunFacing = ["S", "SW", "W", "SE"];
      const extremeIsDry = higherIsDrier(i.indicator);
      const drierAspect = extremeIsDry ? worst : best;
      const solar = sunFacing.includes(drierAspect.band);

      out.push(
        `By aspect, ${worst.band}-facing ground averages ${fmt(worst.mean)} against ` +
          `${fmt(best.mean)} on ${best.band}-facing, a spread of ${fmt(gap)}. ` +
          (solar
            ? `The dry end sits on sun-exposed ${drierAspect.band} faces, which is the ` +
              `insolation pattern expected at this latitude.`
            : `The dry end is on ${drierAspect.band}-facing ground rather than the ` +
              `sun-exposed southerly aspects, so insolation is not what is driving this — ` +
              `land cover or elevation is the more likely explanation.`),
      );
    }
  }

  const ext = i.extremes;
  if (ext.cells > 0) {
    const where: string[] = [];
    if (ext.mean_elevation_m !== null) where.push(`averaging ${ext.mean_elevation_m.toFixed(0)} m`);
    if (ext.mean_slope_deg !== null) where.push(`on ${ext.mean_slope_deg.toFixed(0)}° slopes`);
    if (ext.dominant_aspect !== null && ext.dominant_aspect !== "flat") {
      where.push(`most often ${ext.dominant_aspect}-facing`);
    }
    out.push(
      `The most fire-prone decile is ${ext.cells.toLocaleString()} cells ` +
        `(${(ext.share * 100).toFixed(0)}% of the area) beyond ${fmt(ext.threshold)}` +
        (where.length > 0 ? `, ${where.join(", ")}` : "") +
        `.`,
    );
  }

  if (i.departure !== null) {
    const dep = i.departure;
    out.push(
      dep.drier_share > 0.5
        ? `Against each cell's own twelve-month median, ${(dep.drier_share * 100).toFixed(0)}% of ` +
          `the area is below normal and ${(dep.strongly_drier_share * 100).toFixed(0)}% is ` +
          `substantially below — this is drier than this landscape usually is, not only dry.`
        : `Against each cell's own twelve-month median, only ` +
          `${(dep.drier_share * 100).toFixed(0)}% of the area is below normal, so the ` +
          `conditions in this period are close to what this landscape typically shows.`,
    );
  }

  return out;
}
