"""Pydantic schemas — the single source of truth for the layer's data shapes.

TypeScript never defines these types by hand. ``make schema`` exports this package to JSON
Schema and compiles that to Zod under ``core/src/generated``. CI fails on drift.
"""

from .common import (
    UNITS,
    BBox,
    Confidence,
    DateRange,
    Geometry,
    IndicatorFamily,
    IndicatorId,
    Latitude,
    Longitude,
    MultiPolygon,
    Polygon,
    ServedStatus,
    Severity,
    Strict,
    ValidationStatus,
    indicator_family,
)
from .envelope import (
    CLAIM_ID_PATTERN,
    ConfidenceBasis,
    ConfidenceComponent,
    EnvelopeBase,
    NumericEnvelope,
    RejectedValue,
    SpatialStats,
    SubstrateComponent,
    SubstrateEnvelope,
    SubstrateScore,
    Trend,
    TrendEnvelope,
    ValidationFlag,
    ValidationReport,
    new_claim_id,
)
from .provenance import Method, ProvenanceChain, ProvenanceStep, StepKind
from .responses import (
    AoiCoverage,
    ComparePeriodsRequest,
    ComparePeriodsResponse,
    CoverageRequest,
    CoverageResponse,
    EcologicalStateRequest,
    EcologicalStateResponse,
    ErrorResponse,
    IndicatorComparison,
    IndicatorCoverage,
    ProvenanceRequest,
    ProvenanceResponse,
    ResolvedGeometry,
    SourceRecord,
    SubstrateScoreRequest,
    SubstrateScoreResponse,
)

__all__ = [
    "CLAIM_ID_PATTERN",
    "UNITS",
    "AoiCoverage",
    "BBox",
    "ComparePeriodsRequest",
    "ComparePeriodsResponse",
    "Confidence",
    "ConfidenceBasis",
    "ConfidenceComponent",
    "CoverageRequest",
    "CoverageResponse",
    "DateRange",
    "EcologicalStateRequest",
    "EcologicalStateResponse",
    "EnvelopeBase",
    "ErrorResponse",
    "Geometry",
    "IndicatorComparison",
    "IndicatorCoverage",
    "IndicatorFamily",
    "IndicatorId",
    "Latitude",
    "Longitude",
    "Method",
    "MultiPolygon",
    "NumericEnvelope",
    "Polygon",
    "ProvenanceChain",
    "ProvenanceRequest",
    "ProvenanceResponse",
    "ProvenanceStep",
    "RejectedValue",
    "ResolvedGeometry",
    "ServedStatus",
    "Severity",
    "SourceRecord",
    "SpatialStats",
    "StepKind",
    "Strict",
    "SubstrateComponent",
    "SubstrateEnvelope",
    "SubstrateScore",
    "SubstrateScoreRequest",
    "SubstrateScoreResponse",
    "Trend",
    "TrendEnvelope",
    "ValidationFlag",
    "ValidationReport",
    "ValidationStatus",
    "indicator_family",
    "new_claim_id",
]
